<a href="https://colab.research.google.com/github/komal-shahzada/colab-projects/blob/main/diabeties_predection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

# New Section

In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import VotingClassifier

In [4]:
# Define individual classifiers
svm_model = svm.SVC(kernel='linear', probability=True)
log_model = LogisticRegression()
tree_model = DecisionTreeClassifier()

In [5]:
# Create the hybrid model using soft voting
hybrid_model = VotingClassifier(estimators=[
    ('svm', svm_model),
    ('logistic', log_model),
    ('tree', tree_model)
], voting='soft')

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [7]:
from google.colab import drive
drive.mount('/content/drive')

# Load the dataset, updating the path to the correct location
data = pd.read_csv('/content/drive/MyDrive/diabetes_data_upload.csv') # Replace with your actual file path

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [8]:
# prompt: to connect diabetes_data_upload.csv

# No changes needed to the provided code.  The file is already being loaded
# correctly assuming it exists at the specified path.  If you encounter an error,
# double-check that the path `/content/drive/MyDrive/diabetes_data_upload.csv`
# is accurate.

# ... (rest of your code)
# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Load the CSV file
import pandas as pd

file_path = '/content/drive/MyDrive/diabetes_data_upload.csv'
df = pd.read_csv(file_path)

# Display the first few rows to confirm successful loading
df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
0,40,Male,No,Yes,No,Yes,No,No,No,Yes,No,Yes,No,Yes,Yes,Yes,Positive
1,58,Male,No,No,No,Yes,No,No,Yes,No,No,No,Yes,No,Yes,No,Positive
2,41,Male,Yes,No,No,Yes,Yes,No,No,Yes,No,Yes,No,Yes,Yes,No,Positive
3,45,Male,No,No,Yes,Yes,Yes,Yes,No,Yes,No,Yes,No,No,No,No,Positive
4,60,Male,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Positive

In [9]:
from sklearn.model_selection import train_test_split

# Assuming 'data' contains your features and 'class' is the target variable
X = data.drop('class', axis=1)  # Features (all columns except 'class')
Y = data['class']  # Target variable ('class' column)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)  # Adjust test_size and random_state as needed

In [10]:
# ... (previous code)

# Convert columns with 'Yes'/'No' and 'Male'/'Female' values to numerical (0 and 1)
for column in data.columns:
    if data[column].dtype == 'object':  # Check if column is of object type (likely string)
        # If column contains 'Yes' and 'No', map them to 1 and 0
        if data[column].isin(['Yes', 'No']).all():
            data[column] = data[column].map({'Yes': 1, 'No': 0})
        # If column contains 'Male' and 'Female', map them to 1 and 0
        elif data[column].isin(['Male', 'Female']).all():
            data[column] = data[column].map({'Male': 1, 'Female': 0})

# ... (rest of your code)
X = data.drop('class', axis=1)  # Features (all columns except 'class')
Y = data['class']  # Target variable ('class' column)

# Add Polynomial Features
from sklearn.preprocessing import PolynomialFeatures

# Create polynomial features (degree = 2, you can try different degrees)
poly = PolynomialFeatures(degree=2)
X_poly = poly.fit_transform(X) # Now X contains only numerical data

# Now, use polynomial features in model training
X_train_poly, X_test_poly = train_test_split(X_poly, test_size=0.2, random_state=42)

# Fit the hybrid model with polynomial features
hybrid_model.fit(X_train_poly, Y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

VotingClassifier(estimators=[('svm', SVC(kernel='linear', probability=True)),
                             ('logistic', LogisticRegression()),
                             ('tree', DecisionTreeClassifier())],
                 voting='soft')

In [11]:
# ... (previous code)

# Convert columns with 'Yes'/'No' and 'Male'/'Female' values to numerical (0 and 1)
for column in data.columns:
    if data[column].dtype == 'object':  # Check if column is of object type (likely string)
        # If column contains 'Yes' and 'No', map them to 1 and 0
        if data[column].isin(['Yes', 'No']).all():
            data[column] = data[column].map({'Yes': 1, 'No': 0})
        # If column contains 'Male' and 'Female', map them to 1 and 0
        elif data[column].isin(['Male', 'Female']).all():
            data[column] = data[column].map({'Male': 1, 'Female': 0})

# ... (rest of your code)

# Assuming 'data' contains your features and 'class' is the target variable
X = data.drop('class', axis=1)  # Features (all columns except 'class')
Y = data['class']  # Target variable ('class' column)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)  # Adjust test_size and random_state as needed

# Assuming X_train_res and Y_train_res are supposed to be the training data
# If no specific preprocessing is needed, you can directly use X_train and Y_train
X_train_res = X_train
Y_train_res = Y_train

# Fit the hybrid model to your training data
hybrid_model.fit(X_train_res, Y_train_res)

# ... (rest of your code)

VotingClassifier(estimators=[('svm', SVC(kernel='linear', probability=True)),
                             ('logistic', LogisticRegression()),
                             ('tree', DecisionTreeClassifier())],
                 voting='soft')

In [ ]:
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression

# Define the base models (SVM, Logistic Regression, Decision Tree)
svm_model = svm.SVC(kernel='linear', probability=True)
log_model = LogisticRegression()
tree_model = DecisionTreeClassifier()

# Create Stacking Classifier with base models
estimators = [
    ('svm', svm_model),
    ('logistic', log_model),
    ('tree', tree_model)
]

# Use Logistic Regression as the final estimator
stacking_model = StackingClassifier(estimators=estimators, final_estimator=LogisticRegression())

# Fit the stacking model to the training data
stacking_model.fit(X_train, Y_train)

# Predictions and evaluation (example)
y_pred = stacking_model.predict(X_test)
print("Stacking Model Accuracy: ", accuracy_score(Y_test, y_pred))

Stacking Model Accuracy:  0.9615384615384616

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [ ]:
from sklearn.model_selection import GridSearchCV

# Define parameter grid for each model
param_grid = {
    'svm__C': [0.1, 1, 10],
    'logistic__C': [0.1, 1, 10],
    'tree__max_depth': [5, 10, 15]
}

# Apply GridSearchCV on your hybrid model
grid_search = GridSearchCV(hybrid_model, param_grid, cv=5, n_jobs=-1)
grid_search.fit(X_train, Y_train)
print("Best Parameters:", grid_search.best_params_)

# After grid search, use the best model for prediction
hybrid_model = grid_search.best_estimator_

Best Parameters: {'logistic__C': 0.1, 'svm__C': 0.1, 'tree__max_depth': 5}

In [ ]:
from sklearn.model_selection import cross_val_score

# Perform cross-validation
cv_scores = cross_val_score(hybrid_model, X, Y, cv=5)
print("Cross-validation scores:", cv_scores)
print("Average cross-validation score:", cv_scores.mean())

Cross-validation scores: [0.92307692 0.99038462 0.88461538 0.99038462 0.97115385]
Average cross-validation score: 0.951923076923077

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

# Get predictions
y_pred = hybrid_model.predict(X_test)

# Confusion Matrix
cm = confusion_matrix(Y_test, y_pred)
print("Confusion Matrix:\n", cm)

# Classification Report
cr = classification_report(Y_test, y_pred)
print("Classification Report:\n", cr)

Confusion Matrix:
 [[37  3]
 [ 1 63]]
Classification Report:
               precision    recall  f1-score   support

    Negative       0.97      0.93      0.95        40
    Positive       0.95      0.98      0.97        64

    accuracy                           0.96       104
   macro avg       0.96      0.95      0.96       104
weighted avg       0.96      0.96      0.96       104

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# loading the diabetes dataset to a pandas DataFrame
diabetes_dataset = pd.read_csv('/content/drive/MyDrive/diabetes_data_upload.csv') # Update the path

In [ ]:
pd.read_csv?

In [ ]:
# printing the first 5 rows of the dataset
diabetes_dataset.head()

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
0,40,Male,No,Yes,No,Yes,No,No,No,Yes,No,Yes,No,Yes,Yes,Yes,Positive
1,58,Male,No,No,No,Yes,No,No,Yes,No,No,No,Yes,No,Yes,No,Positive
2,41,Male,Yes,No,No,Yes,Yes,No,No,Yes,No,Yes,No,Yes,Yes,No,Positive
3,45,Male,No,No,Yes,Yes,Yes,Yes,No,Yes,No,Yes,No,No,No,No,Positive
4,60,Male,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Positive

In [ ]:
# number of rows and Columns in this dataset
diabetes_dataset.shape

(520, 17)

In [ ]:
# getting the statistical measures of the data
diabetes_dataset.describe()

              Age
count  520.000000
mean    48.028846
std     12.151466
min     16.000000
25%     39.000000
50%     47.500000
75%     57.000000
max     90.000000

In [ ]:
# Check the column names in your DataFrame
print(diabetes_dataset.columns)

# If the 'Outcome' column is not present, or has a different name,
# correct the column name in the following line to match the actual column name

# Assuming the actual column name is 'class', replace 'old_name' with 'class'
diabetes_dataset = diabetes_dataset.rename(columns={'class': 'Outcome'})

# If 'Outcome' column is mislabeled, you can select the correct column by index
# For example, if 'Outcome' is in the 5th column (index 4):
# diabetes_dataset['Outcome'] = diabetes_dataset.iloc[:, 4]

# Then, you should be able to run the following line without error:
diabetes_dataset['Outcome'].value_counts()

Index(['Age', 'Gender', 'Polyuria', 'Polydipsia', 'sudden weight loss',
       'weakness', 'Polyphagia', 'Genital thrush', 'visual blurring',
       'Itching', 'Irritability', 'delayed healing', 'partial paresis',
       'muscle stiffness', 'Alopecia', 'Obesity', 'class'],
      dtype='object')

Outcome
Positive    320
Negative    200
Name: count, dtype: int64

In [ ]:
# Convert columns with 'Yes'/'No' values to numerical (0 and 1)
for column in diabetes_dataset.columns:
    if diabetes_dataset[column].dtype == 'object':  # Check if column is of object type (likely string)
        # If column contains 'Yes' and 'No', map them to 1 and 0
        if diabetes_dataset[column].isin(['Yes', 'No']).all():
            diabetes_dataset[column] = diabetes_dataset[column].map({'Yes': 1, 'No': 0})
        # If column contains 'Male' and 'Female', map them to 1 and 0 # Added this condition
        elif diabetes_dataset[column].isin(['Male', 'Female']).all():
            diabetes_dataset[column] = diabetes_dataset[column].map({'Male': 1, 'Female': 0})

# Now, calculate the mean for each group based on 'Outcome'
diabetes_dataset.groupby('Outcome').mean()

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity
Outcome,,,,,,,,,,,,,,,,
Negative,46.360000,0.905000,0.075000,0.040000,0.1450,0.43500,0.240000,0.165000,0.290000,0.49500,0.08000,0.430000,0.16,0.300000,0.50500,0.135000
Positive,49.071875,0.459375,0.759375,0.703125,0.5875,0.68125,0.590625,0.259375,0.546875,0.48125,0.34375,0.478125,0.60,0.421875,0.24375,0.190625

In [ ]:
# separating the data and labels
X = diabetes_dataset.drop(columns = 'Outcome', axis=1)
Y = diabetes_dataset['Outcome']

In [ ]:
print(X)

     Age  Gender  Polyuria  Polydipsia  sudden weight loss  weakness  \
0     40       1         0           1                   0         1
1     58       1         0           0                   0         1
2     41       1         1           0                   0         1
3     45       1         0           0                   1         1
4     60       1         1           1                   1         1
..   ...     ...       ...         ...                 ...       ...
515   39       0         1           1                   1         0
516   48       0         1           1                   1         1
517   58       0         1           1                   1         1
518   32       0         0           0                   0         1
519   42       1         0           0                   0         0

     Polyphagia  Genital thrush  visual blurring  Itching  Irritability  \
0             0               0                0        1             0
1             0               0                1        0             0
2             1               0                0        1             0
3             1               1                0        1             0
4             1               0                1        1             1
..          ...             ...              ...      ...           ...
515           1               0                0        1             0
516           1               0                0        1             1
517           1               0                1        0             0
518           0               0                1        1             0
519           0               0                0        0             0

     delayed healing  partial paresis  muscle stiffness  Alopecia  Obesity
0                  1                0                 1         1        1
1                  0                1                 0         1        0
2                  1                0                 1         1        0
3                  1                0                 0         0        0
4                  1                1                 1         1        1
..               ...              ...               ...       ...      ...
515                1                1                 0         0        0
516                1                1                 0         0        0
517                0                1                 1         0        1
518                1                0                 0         1        0
519                0                0                 0         0        0

[520 rows x 16 columns]

In [ ]:
print(Y)

0      Positive
1      Positive
2      Positive
3      Positive
4      Positive
         ...
515    Positive
516    Positive
517    Positive
518    Negative
519    Negative
Name: Outcome, Length: 520, dtype: object

In [ ]:
scaler = StandardScaler()

In [ ]:
scaler.fit(X)

StandardScaler()

In [ ]:
standardized_data = scaler.transform(X)

In [ ]:
print(standardized_data)

[[-0.6613669   0.76509206 -0.99233705 ...  1.29099445  1.38022749
   2.21564684]
 [ 0.82136224  0.76509206 -0.99233705 ... -0.77459667  1.38022749
  -0.45133547]
 [-0.57899306  0.76509206  1.00772212 ...  1.29099445  1.38022749
  -0.45133547]
 ...
 [ 0.82136224 -1.30703226  1.00772212 ...  1.29099445 -0.72451824
   2.21564684]
 [-1.32035762 -1.30703226 -0.99233705 ... -0.77459667  1.38022749
  -0.45133547]
 [-0.49661921  0.76509206 -0.99233705 ... -0.77459667 -0.72451824
  -0.45133547]]

In [ ]:
X = standardized_data
Y = diabetes_dataset['Outcome']

In [ ]:
print(X)
print(Y)

[[-0.6613669   0.76509206 -0.99233705 ...  1.29099445  1.38022749
   2.21564684]
 [ 0.82136224  0.76509206 -0.99233705 ... -0.77459667  1.38022749
  -0.45133547]
 [-0.57899306  0.76509206  1.00772212 ...  1.29099445  1.38022749
  -0.45133547]
 ...
 [ 0.82136224 -1.30703226  1.00772212 ...  1.29099445 -0.72451824
   2.21564684]
 [-1.32035762 -1.30703226 -0.99233705 ... -0.77459667  1.38022749
  -0.45133547]
 [-0.49661921  0.76509206 -0.99233705 ... -0.77459667 -0.72451824
  -0.45133547]]
0      Positive
1      Positive
2      Positive
3      Positive
4      Positive
         ...
515    Positive
516    Positive
517    Positive
518    Negative
519    Negative
Name: Outcome, Length: 520, dtype: object

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, stratify=Y, random_state=2)

In [ ]:
print(X.shape, X_train.shape, X_test.shape)

(520, 16) (416, 16) (104, 16)

In [ ]:
classifier = svm.SVC(kernel='linear')

In [ ]:
#training the support vector Machine Classifier
classifier.fit(X_train, Y_train)

SVC(kernel='linear')

In [ ]:
# accuracy score on the training data
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [ ]:
print('Accuracy score of the training data : ', training_data_accuracy)

Accuracy score of the training data :  0.9423076923076923

In [ ]:
# accuracy score on the test data
X_test_prediction = classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [ ]:
print('Accuracy score of the test data : ', test_data_accuracy)

Accuracy score of the test data :  0.9326923076923077

In [ ]:
input_data = (1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1) # Replace with actual values for all 16 features


# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

# standardize the input data
std_data = scaler.transform(input_data_reshaped)
print(std_data)

prediction = classifier.predict(std_data)
print(prediction)

if (prediction[0] == 0):
  print('The person is not diabetic')
else:
  print('The person is diabetic')

[[-3.87394669  0.76509206  1.00772212  1.10984668  1.18165704  0.83959397
   1.09274555  1.86621505  1.10984668  1.02729546  1.76832806  1.08431186
   1.14953407  1.29099445  1.38022749  2.21564684]]
['Positive']
The person is diabetic

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(